# Generated by Django 3.2.7 on 2021-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=0),
        ),
    ]
