# Generated by Django 3.2.7 on 2021-09-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_detail',
            options={'ordering': ['id']},
        ),
    ]
